[package]
name = "day7"
version = "0.1.0"
authors = ["Alex Novak <alex@alexnovak.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
